/* NYC Baby city intelligence — factual public-source leads, summarized in NYC Baby's own voice. No third-party reviews are reproduced. */
window.NYCBABY_CITY = {
  updated: '2026-09-06',
  restaurants: [
    {name:'20 Blocks',area:'East Village',kind:'Sandwiches',why:'New Hit List pick · lunch, brunch, coffee',moods:['SOLO','DAYTIME','VISITOR'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Frenzie',area:'Brooklyn Heights',kind:'Pizza',why:'Walk-in-only · casual dinner · late-night option',moods:['DATE','GROUP','AFTER WORK'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Cospa Ramen',area:'NoMad',kind:'Japanese',why:'Affordable ramen · open late · easy solo stop',moods:['SOLO','AFTER WORK','LATE'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Keepers',area:'West Village',kind:'Pizza + Bar',why:'Bar seats · pizza · easy spontaneous night',moods:['DATE','AFTER WORK','SOCIAL'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Lala Hot Chicken',area:'Chelsea',kind:'Fried Chicken',why:'Casual · solo-friendly · inexpensive',moods:['SOLO','CASUAL','AFTER WORK'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Masani',area:'Forest Hills',kind:'Pizza',why:'Casual neighborhood pizza · good low-pressure group plan',moods:['CASUAL','GROUP','FAMILY'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:"Sam Ping's BBQ",area:'Financial District',kind:'Chinese BBQ',why:'Fast inexpensive lunch · useful workday stop',moods:['SOLO','DAYTIME','WORKDAY'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Hungry Spicy',area:'Chelsea',kind:'Thai',why:'Big-group energy · memorable dinner plan',moods:['GROUP','SOCIAL','VISITOR'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Burmese Bites',area:'Astoria',kind:'Burmese',why:'Casual · group-friendly · good for out-of-towners',moods:['GROUP','VISITOR','DATE'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Zig Zag Oyster Bar',area:'Prospect Heights',kind:'Raw Bar',why:'Walk-in-only · bar seating · spontaneous date or social stop',moods:['DATE','SOLO','AFTER WORK'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Graciela',area:'West Village',kind:'Argentinian',why:'Date night · parents in town · special occasion',moods:['DATE','VISITOR','SPECIAL'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Prosciutto',area:'East Village',kind:'Italian',why:'Small room · walk-in energy · easy solo dinner',moods:['SOLO','DATE','AFTER WORK'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Bark Barbecue',area:'Bushwick',kind:'BBQ',why:'Dominican-Texan barbecue · built for sharing',moods:['GROUP','VISITOR','WEEKEND'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Phê',area:'Chinatown',kind:'Vietnamese',why:'Calm daytime stop · coffee · easy alone',moods:['SOLO','DAYTIME','VISITOR'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Consuelo',area:'Upper West Side',kind:'Mexican',why:'Neighborhood option · brunch, date or solo dinner',moods:['DATE','SOLO','NEIGHBORHOOD'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Titán',area:'DUMBO',kind:'Mexican',why:'Big backyard · easy group plan',moods:['GROUP','VISITOR','WEEKEND'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Oriana',area:'Nolita',kind:'American',why:'Polished · groups, occasions and team dinners',moods:['GROUP','SPECIAL','WORK'],source:'The Infatuation · Hit List',url:'https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list'},
    {name:'Faux',area:'Tribeca',kind:'French',why:'New opening · dinner + late-night energy',moods:['DATE','LATE','AFTER WORK'],source:'The Infatuation · New Openings',url:'https://www.theinfatuation.com/new-york/guides/new-nyc-restaurants-openings'},
    {name:"Wu’s Dynasty",area:'Upper West Side',kind:'Chinese',why:'New neighborhood opening · useful for UWS members',moods:['NEIGHBORHOOD','GROUP','FAMILY'],source:'The Infatuation · New Openings',url:'https://www.theinfatuation.com/new-york/guides/new-nyc-restaurants-openings'}
  ],
  activities: [
    {date:'SEP 7',name:'Whitney Biennial Tour',area:'Whitney Museum',why:'1 PM · easy solo culture plan',tag:'CULTURE',moods:['SOLO','VISITOR','DAYTIME'],url:'https://whitney.org/events'},
    {date:'SEP 7',name:'A Closer Look',area:'Whitney Museum',why:'12 PM · guided close-looking through dialogue',tag:'SOCIAL CULTURE',moods:['SOLO','SOCIAL','DAYTIME'],url:'https://whitney.org/events'},
    {date:'SEP 9',name:'The Art of Minnie Evans: A Conversation',area:'Whitney Museum',why:'5:30–7 PM · talks + readings',tag:'AFTER WORK',moods:['SOLO','AFTER WORK','CULTURE'],url:'https://whitney.org/events'},
    {date:'SEP 9',name:'Whitney Biennial Tour',area:'Whitney Museum',why:'1 PM · plug a visitor into the city while you work',tag:'GUEST-FRIENDLY',moods:['VISITOR','DAYTIME','SOLO'],url:'https://whitney.org/events'},
    {date:'SEP 11',name:'Free Friday Nights',area:'Whitney Museum',why:'5–10 PM · high-value social/culture plan',tag:'COME SOLO',moods:['SOLO','SOCIAL','NO DRINKS'],url:'https://whitney.org/events'},
    {date:'SEP 11',name:'Date Night at The Met',area:'Upper East Side',why:'Live music + art · 5 PM · come solo or bring someone',tag:'SOCIAL',moods:['DATE','SOLO','CULTURE'],url:'https://www.metmuseum.org/events'},
    {date:'SEP 13',name:'Free Second Sunday',area:'Whitney Museum',why:'10:30 AM–6 PM · easy Sunday plan',tag:'FREE',moods:['SOLO','VISITOR','WEEKEND'],url:'https://whitney.org/events'},
    {date:'SEP 18',name:'Whitney Free Friday + Ailey',area:'Whitney Museum',why:'Free dance classes + DJ + art · 5–10 PM',tag:'SOCIAL',moods:['SOLO','SOCIAL','ACTIVE'],url:'https://whitney.org/events'},
    {date:'SEP 18',name:'Date Night at The Met',area:'Upper East Side',why:'Friday culture plan · live music + art',tag:'SOCIAL',moods:['DATE','SOLO','CULTURE'],url:'https://www.metmuseum.org/events'},
    {date:'SEP 21',name:'Chuseok Celebration',area:'City Hall',why:'Public cultural celebration · 5:30 PM',tag:'COMMUNITY',moods:['SOCIAL','COMMUNITY','CULTURE'],url:'https://www.nyc.gov/'},
    {date:'SEP 22',name:'Climate Week at City Hall',area:'City Hall',why:'Civic + climate community · 5:30 PM',tag:'CAUSES',moods:['CAUSES','SOCIAL','AFTER WORK'],url:'https://www.nyc.gov/'},
    {date:'SEP 25',name:'Free Friday Nights',area:'Whitney Museum',why:'5–10 PM · art + people + a reason to leave home',tag:'COME SOLO',moods:['SOLO','SOCIAL','NO DRINKS'],url:'https://whitney.org/events'},
    {date:'SEP 25',name:'Date Night at The Met',area:'Upper East Side',why:'Friday culture plan · 5 PM',tag:'SOCIAL',moods:['DATE','SOLO','CULTURE'],url:'https://www.metmuseum.org/events'}
  ]
};

(function(){
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const labels={restaurants:['ALL','SOLO','DATE','GROUP','VISITOR','AFTER WORK'],activities:['ALL','SOLO','SOCIAL','VISITOR','AFTER WORK','NO DRINKS']};
  let currentType='restaurants',currentFilter='ALL';
  function modal(){let m=document.getElementById('cityHubModal');if(!m){m=document.createElement('div');m.id='cityHubModal';m.className='modal';m.onclick=e=>{if(e.target===m)m.classList.remove('open')};document.body.appendChild(m)}return m}
  function matches(x){return currentFilter==='ALL'||(x.moods||[]).includes(currentFilter)}
  function render(){const m=modal(),data=(window.NYCBABY_CITY[currentType]||[]).filter(matches);const isR=currentType==='restaurants';const filters=labels[currentType].map(f=>`<button onclick="window.filterCityHub('${f}')" style="padding:7px 10px;border-radius:999px;border:1px solid #3b4850;background:${f===currentFilter?'#f2f0ea':'#11191e'};color:${f===currentFilter?'#111':'#dbe1e5'};font-size:9px">${f}</button>`).join('');const cards=data.map((x,i)=>`<div style="border:1px solid #2b363d;border-radius:10px;padding:13px;background:#0f171c;margin-bottom:8px"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><div style="font-size:8px;letter-spacing:1.3px;color:#8e9aa2">${esc(isR?x.area:x.date+' · '+x.area)}</div><h4 style="margin:5px 0;font-size:15px">${esc(x.name)}</h4><div style="font-size:10px;color:#b9c2c8">${esc(isR?x.kind+' · '+x.why:x.why)}</div></div><span style="font-size:8px;border:1px solid #3a474f;border-radius:999px;padding:5px 7px;white-space:nowrap">${esc(isR?(x.moods||[])[0]||'PLAN':x.tag)}</span></div><div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:11px"><button class="light" onclick="show('${isR?'Finding someone to join you at':'Finding people for'} ${esc(x.name)}')">${isR?'FIND COMPANY':'WHO\'S GOING?'}</button><button onclick="openButler('${esc(isR?'Build a night around '+x.name:'Build me a plan around '+x.name)}');document.getElementById('cityHubModal').classList.remove('open')">BUILD A PLAN</button><a href="${esc(x.url||'#')}" target="_blank" rel="noopener" style="display:inline-flex;align-items:center;text-decoration:none;border:1px solid #4b565d;color:#dbe1e5;border-radius:999px;padding:9px 12px;font-size:9px">SOURCE ↗</a></div></div>`).join('');m.innerHTML=`<div class="modalCard" style="width:min(820px,94vw);max-height:86vh;overflow:auto"><button class="close" onclick="document.getElementById('cityHubModal').classList.remove('open')">×</button><p class="kicker">${isR?'NYC BABY · WHERE SHOULD WE EAT?':'NYC BABY · GET ME OUT OF THE HOUSE'}</p><h3>${isR?'Eat somewhere worth leaving home for.':'Your apartment is not the whole city.'}</h3><p>${isR?'Current openings and standouts become social plans: go alone, bring a guest, or let NYC Baby find you company.':'Culture, community and low-friction plans designed so showing up alone never feels weird.'}</p><div style="display:flex;gap:6px;flex-wrap:wrap;margin:14px 0 18px">${filters}</div>${cards||'<p>No matches yet. NYC Baby will keep looking.</p>'}<p style="margin-top:18px;font-size:9px;line-height:1.5;color:#87949c">Updated ${window.NYCBABY_CITY.updated}. Restaurant facts are summarized from current public Infatuation guides; activity facts from official/public event calendars. NYC Baby does not reproduce third-party reviews—it adds plan, guest and social context.</p></div>`;m.classList.add('open')}
  window.openCityHub=function(type,filter='ALL'){currentType=type;currentFilter=filter;render()};window.filterCityHub=function(filter){currentFilter=filter;render()};
})();

/* Hamptons-only fall layer. Deliberately replaces only #out-east; no other homepage section is touched. */
(function(){
  function buildHamptons(){
    const s=document.getElementById('out-east'); if(!s)return;
    s.innerHTML=`<div class="sectionHead"><div><p class="kicker">GOING OUT EAST · FALL 2026</p><h3>The Hamptons didn't end on Labor Day.</h3><p>Real fall plans, real restaurants and the East End when it finally gets a little easier.</p></div><button class="textBtn" onclick="openButler('What should we do in the Hamptons this fall?')">What are we doing? →</button></div>
    <div class="cardGrid four" style="margin-top:16px">
      <article class="eventCard"><img src="https://images.unsplash.com/photo-1500534314209-a25ddb2bd4297?auto=format&fit=crop&w=900&q=85"><div class="badge">OCT 10 · EAST HAMPTON</div><div class="cardBody"><h4>ARF Stroll to the Sea</h4><p>Mulford Farm → Main Beach · 9 AM</p><small>Dan's Papers' confirmed fall pick: the annual dog walk, vendors and community scene.</small><button onclick="openButler('Build a Saturday around the ARF Stroll to the Sea in East Hampton')">BUILD THE DAY</button></div></article>
      <article class="eventCard"><img src="https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=85"><div class="badge">FALL · SAGAPONACK</div><div class="cardBody"><h4>Wölffer in Harvest Season</h4><p>Wine · vineyard · crisp afternoon</p><small>The tasting room is a year-round fall anchor. Easy before dinner in Sag Harbor or Bridgehampton.</small><button onclick="openButler('Build me a fall afternoon at Wolffer and dinner after')">I'M IN</button></div></article>
      <article class="eventCard"><img src="https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=85"><div class="badge">FALL · WATER MILL</div><div class="cardBody"><h4>Parrish Art Museum</h4><p>Water Mill · Thursday–Monday</p><small>A real off-season anchor: exhibitions, programs and an easy culture-first afternoon.</small><button onclick="openButler('Build me a Parrish Art Museum afternoon and dinner')">MAKE IT A PLAN</button></div></article>
      <article class="eventCard"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=85"><div class="badge">NEW + YEAR-ROUND</div><div class="cardBody"><h4>Miracle · Sag Harbor</h4><p>29 Main Street</p><small>New in 2026, built for lunch, dinner and cocktails beyond summer. This is the kind of fall opening IN should know.</small><button onclick="openButler('Plan dinner at Miracle in Sag Harbor')">WHAT'S THE MOVE?</button></div></article>
    </div>
    <div class="sectionHead" style="margin-top:28px"><div><p class="kicker">DINNER AFTER LABOR DAY</p><h3>Places actually worth building the night around.</h3></div></div>
    <div class="cardGrid four" style="margin-top:16px">
      <article class="eventCard"><div class="badge">SAG HARBOR</div><div class="cardBody"><h4>Page Sag Harbor</h4><p>63 Main Street · year-round</p><small>Warm, central, reliable off-season bar-and-dinner energy.</small><button onclick="openButler('Build a fall night around Page Sag Harbor')">GET US IN</button></div></article>
      <article class="eventCard"><div class="badge">NOYAC / SAG HARBOR</div><div class="cardBody"><h4>Bell & Anchor</h4><p>3253 Noyack Road</p><small>Waterfront seafood, oysters, cocktails and a dinner that still feels Out East after summer.</small><button onclick="openButler('Build a fall dinner around Bell and Anchor')">GET US IN</button></div></article>
      <article class="eventCard"><div class="badge">SAG HARBOR</div><div class="cardBody"><h4>Lulu Kitchen & Bar</h4><p>126 Main Street</p><small>Wood-fired Mediterranean, cocktails and a polished Main Street night.</small><button onclick="openButler('Build a fall night around Lulu Sag Harbor')">GET US IN</button></div></article>
      <article class="eventCard"><div class="badge">EAST HAMPTON · YEAR-ROUND</div><div class="cardBody"><h4>Highway</h4><p>290 Montauk Highway</p><small>Seasonal New American and exactly the kind of neighborhood dinner that works when summer is over.</small><button onclick="openButler('Build a fall East Hampton dinner around Highway')">GET US IN</button></div></article>
    </div>
    <div class="panel" style="margin-top:16px;padding:22px"><p class="kicker">THE FALL MOVE</p><h3 style="margin-top:6px">What are you up to Out East?</h3><p>Don't make me scroll. Show me who's around, what is actually happening, and where we can eat after.</p><div class="heroActions" style="margin-top:12px"><button onclick="show('Looking for your people Out East')">WHO'S OUT EAST?</button><button onclick="openButler('What are we going to do in the Hamptons this weekend?')">WHAT ARE WE GOING TO DO?</button><button onclick="openButler('Find me a real fall Hamptons dinner')">DINNER TONIGHT</button></div></div>`;
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildHamptons);else buildHamptons();
})();