const express=require('express');
const cors=require('cors');
const crypto=require('crypto');
const Stripe=require('stripe');
const {Pool}=require('pg');
const {registerAgentRoutes,createRun,latestFor}=require('./agent-engine');
const app=express();app.use(cors());
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const db=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;
const foundingMembers=['grant','mikey','falconi','stuart','marney'];
const state={signals:[],invites:[],paidMembers:[],activity:[],datingProfiles:[],introRequests:[],networkInvites:[],networkMembers:[]};
function normalize(x){return String(x||'').trim().toLowerCase()}
function displayName(x){return String(x||'').trim().replace(/\s+/g,' ').slice(0,80)}
function allMemberIds(){return [...new Set([...foundingMembers,...state.networkMembers.map(x=>x.id)])]}
function overlaps(){const by={};for(const s of state.signals){if(!s.item)continue;(by[s.item]??=[]).push(s)}return Object.entries(by).map(([item,arr])=>{const people=[...new Set(arr.map(x=>x.member))];return people.length<2?null:{item,people,score:people.length,latest:arr.at(-1).createdAt}}).filter(Boolean).sort((a,b)=>b.score-a.score)}
async function initDb(){if(!db)return;await db.query(`CREATE TABLE IF NOT EXISTS in_network_invites(id text primary key,token text unique not null,inviter text not null,name text not null,contact text,status text not null,created_at timestamptz not null,opened_at timestamptz,joined_at timestamptz,member_id text);CREATE TABLE IF NOT EXISTS in_network_members(id text primary key,name text not null,contact text,invited_by text,invite_token text unique,interests jsonb not null default '[]'::jsonb,open_to_meet boolean not null default false,gender text,interested_in text,joined_at timestamptz not null);`);const [ir,mr]=await Promise.all([db.query('SELECT * FROM in_network_invites ORDER BY created_at'),db.query('SELECT * FROM in_network_members ORDER BY joined_at')]);state.networkInvites=ir.rows.map(r=>({id:r.id,token:r.token,from:r.inviter,name:r.name,contact:r.contact||'',status:r.status,createdAt:r.created_at?.toISOString(),openedAt:r.opened_at?.toISOString()||null,joinedAt:r.joined_at?.toISOString()||null,memberId:r.member_id||null}));state.networkMembers=mr.rows.map(r=>({id:r.id,name:r.name,contact:r.contact||'',invitedBy:r.invited_by,inviteToken:r.invite_token,interests:r.interests||[],openToMeet:r.open_to_meet,gender:r.gender||'',interestedIn:r.interested_in||'',joinedAt:r.joined_at?.toISOString()}));for(const m of state.networkMembers)if(m.openToMeet&&!state.datingProfiles.some(x=>x.member===m.id))state.datingProfiles.push({member:m.id,gender:m.gender,interestedIn:m.interestedIn,open:true,updatedAt:m.joinedAt});console.log('IN persistence loaded',state.networkMembers.length,'members',state.networkInvites.length,'invites')}
async function saveInvite(r){if(!db)return;await db.query(`INSERT INTO in_network_invites(id,token,inviter,name,contact,status,created_at,opened_at,joined_at,member_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,opened_at=EXCLUDED.opened_at,joined_at=EXCLUDED.joined_at,member_id=EXCLUDED.member_id,contact=EXCLUDED.contact`,[r.id,r.token,r.from,r.name,r.contact,r.status,r.createdAt,r.openedAt,r.joinedAt,r.memberId])}
async function saveMember(m){if(!db)return;await db.query(`INSERT INTO in_network_members(id,name,contact,invited_by,invite_token,interests,open_to_meet,gender,interested_in,joined_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,contact=EXCLUDED.contact,interests=EXCLUDED.interests,open_to_meet=EXCLUDED.open_to_meet,gender=EXCLUDED.gender,interested_in=EXCLUDED.interested_in`,[m.id,m.name,m.contact,m.invitedBy,m.inviteToken,JSON.stringify(m.interests),m.openToMeet,m.gender,m.interestedIn,m.joinedAt])}
app.post('/api/billing/webhook',express.raw({type:'application/json'}),(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Billing not configured');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send('Invalid webhook signature')}const o=event.data.object;if(event.type==='checkout.session.completed')state.paidMembers.push({email:normalize(o.customer_details&&o.customer_details.email),customer:o.customer,subscription:o.subscription,status:'paid',createdAt:new Date().toISOString()});res.json({received:true})});
app.use(express.json({limit:'1mb'}));
app.get('/health',(req,res)=>{const latest=latestFor('mikey');res.json({ok:true,service:'IN shared-signal API',billing:!!stripe,persistence:db?'postgres':'memory',members:allMemberIds().length,agents:{enabled:true,total:500,modelConfigured:!!process.env.OPENAI_API_KEY,latest:latest?{id:latest.id,status:latest.status,completed:latest.completed,aiCompleted:latest.aiCompleted}:null}})});
app.get('/api/state',(req,res)=>{const member=normalize(req.query.member||'grant');res.json({member,members:allMemberIds(),signals:state.signals,overlaps:overlaps(),invites:state.invites.filter(x=>x.to===member||x.from===member)})});
app.post('/api/signal',(req,res)=>{const member=normalize(req.body.member),item=normalize(req.body.item),value=String(req.body.value||'');if(!member||!item||!value)return res.status(400).json({error:'member, item, value required'});const rec={id:Date.now()+'-'+Math.random().toString(36).slice(2,7),member,item,value,createdAt:new Date().toISOString()};state.signals.push(rec);if(state.signals.length>5000)state.signals.splice(0,state.signals.length-5000);res.json({ok:true,signal:rec,overlaps:overlaps()})});
app.post('/api/invite',(req,res)=>{const from=normalize(req.body.from),to=normalize(req.body.to),item=normalize(req.body.item);if(!from||!to||!item)return res.status(400).json({error:'from, to, item required'});const rec={id:Date.now()+'-'+Math.random().toString(36).slice(2,7),from,to,item,status:'open',createdAt:new Date().toISOString()};state.invites.push(rec);res.json({ok:true,invite:rec})});
app.post('/api/activity',(req,res)=>{const member=normalize(req.body.member),event=normalize(req.body.event),detail=String(req.body.detail||''),sessionId=String(req.body.sessionId||'').slice(0,120);if(!member||!event)return res.status(400).json({error:'member and event required'});const rec={id:Date.now()+'-'+Math.random().toString(36).slice(2,7),member,event,detail,sessionId,createdAt:new Date().toISOString()};state.activity.push(rec);if(state.activity.length>1000)state.activity.splice(0,state.activity.length-1000);console.log('ACTIVITY',JSON.stringify(rec));res.json({ok:true,activity:rec})});
app.get('/api/activity',(req,res)=>{const member=normalize(req.query.member||'mikey'),rows=state.activity.filter(x=>x.member===member).slice(-200).reverse(),sessions=[...new Set(rows.map(x=>x.sessionId).filter(Boolean))];res.json({member,count:rows.length,sessions:sessions.length,lastActive:rows[0]?.createdAt||null,activity:rows})});
app.post('/api/network/invite',async(req,res)=>{try{const from=normalize(req.body.from),name=displayName(req.body.name),contact=String(req.body.contact||'').trim().slice(0,160);if(!from||!name)return res.status(400).json({error:'from and name required'});const token=crypto.randomBytes(18).toString('hex'),rec={id:'in-'+Date.now(),token,from,name,contact,status:'sent',createdAt:new Date().toISOString(),openedAt:null,joinedAt:null,memberId:null};state.networkInvites.push(rec);await saveInvite(rec);const url=(process.env.IN_SITE_URL||'https://nyc-baby.onrender.com')+'/accept-in.html?token='+token;console.log('NETWORK_INVITE',JSON.stringify({...rec,url}));res.json({ok:true,invite:{...rec,url}})}catch(e){console.error('network invite',e);res.status(500).json({error:'Could not create invite'})}});
app.get('/api/network/invite/:token',async(req,res)=>{try{const rec=state.networkInvites.find(x=>x.token===req.params.token);if(!rec)return res.status(404).json({error:'Invite not found'});if(!rec.openedAt){rec.openedAt=new Date().toISOString();rec.status=rec.status==='joined'?'joined':'opened';await saveInvite(rec)}res.json({invite:{token:rec.token,from:rec.from,name:rec.name,status:rec.status,createdAt:rec.createdAt}})}catch(e){res.status(500).json({error:'Could not open invite'})}});
app.post('/api/network/join',async(req,res)=>{try{const token=String(req.body.token||''),rec=state.networkInvites.find(x=>x.token===token);if(!rec)return res.status(404).json({error:'Invite not found'});if(rec.status==='joined'){const existing=state.networkMembers.find(x=>x.id===rec.memberId);return res.json({ok:true,member:existing,alreadyJoined:true})}const name=displayName(req.body.name||rec.name),contact=String(req.body.contact||rec.contact||'').trim().slice(0,160),interests=Array.isArray(req.body.interests)?req.body.interests.map(x=>String(x).slice(0,40)).slice(0,12):[],openToMeet=!!req.body.openToMeet,gender=normalize(req.body.gender),interestedIn=normalize(req.body.interestedIn);if(!name)return res.status(400).json({error:'Name required'});let base=normalize(name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'member',id=base,n=2;while(allMemberIds().includes(id))id=base+'-'+n++;const member={id,name,contact,invitedBy:rec.from,inviteToken:token,interests,openToMeet,gender,interestedIn,joinedAt:new Date().toISOString()};state.networkMembers.push(member);rec.status='joined';rec.joinedAt=member.joinedAt;rec.memberId=id;if(openToMeet)state.datingProfiles.push({member:id,gender,interestedIn,open:true,updatedAt:member.joinedAt});await saveMember(member);await saveInvite(rec);console.log('NETWORK_JOIN',JSON.stringify(member));res.json({ok:true,member})}catch(e){console.error('network join',e);res.status(500).json({error:'Could not join IN'})}});
app.get('/api/network/members',(req,res)=>res.json({count:state.networkMembers.length,members:state.networkMembers.slice().reverse(),foundingMembers,invites:state.networkInvites.slice().reverse().map(x=>({id:x.id,from:x.from,name:x.name,status:x.status,createdAt:x.createdAt,openedAt:x.openedAt,joinedAt:x.joinedAt,memberId:x.memberId})),persistence:db?'postgres':'memory'}));
app.get('/api/network/invites',(req,res)=>{const from=normalize(req.query.from||''),rows=state.networkInvites.filter(x=>!from||x.from===from).slice().reverse();res.json({count:rows.length,invites:rows.map(x=>({id:x.id,token:x.token,from:x.from,name:x.name,contact:x.contact,status:x.status,createdAt:x.createdAt,openedAt:x.openedAt,joinedAt:x.joinedAt,memberId:x.memberId,url:(process.env.IN_SITE_URL||'https://nyc-baby.onrender.com')+'/accept-in.html?token='+x.token})),persistence:db?'postgres':'memory'})});
app.post('/api/dating/profile',(req,res)=>{const member=normalize(req.body.member),gender=normalize(req.body.gender),interestedIn=normalize(req.body.interestedIn),open=!!req.body.open;if(!member)return res.status(400).json({error:'member required'});let p=state.datingProfiles.find(x=>x.member===member);if(!p){p={member};state.datingProfiles.push(p)}Object.assign(p,{gender,interestedIn,open,updatedAt:new Date().toISOString()});res.json({ok:true,profile:p})});
function datingOptions(member){const me=state.datingProfiles.find(x=>x.member===member);return state.datingProfiles.filter(x=>x.member!==member&&x.open&&(!me?.interestedIn||me.interestedIn==='any'||x.gender===me.interestedIn)&&(!x.interestedIn||x.interestedIn==='any'||x.interestedIn===me?.gender)).map((x,i)=>({id:'intro-'+x.member,type:'INTRODUCTION',label:'TRUSTED INTRO',title:'Someone in your network is open to meeting.',detail:'There is mutual openness. IN can ask both sides privately before revealing identities or arranging anything.',candidate:x.member,score:95-i,status:'available'}))}
app.get('/api/fuck-it/options',(req,res)=>{const member=normalize(req.query.member||'mikey'),intent=normalize(req.query.intent||'anything');let options=[];if(intent==='meet someone'||intent==='meet-someone'||intent==='meet_someone')options=datingOptions(member);if(!options.length)options=[{id:'open-intro',type:'INTRO_SEARCH',label:'INTRODUCTION SEARCH',title:'Open the network.',detail:'Tell IN you are open to meeting someone tonight. We will only surface a real introduction when another opted-in person is compatible.',score:88,status:'searching'},{id:'social-bridge',type:'SOCIAL_BRIDGE',label:'WIDEN THE GRAPH',title:'Create the room first.',detail:'Pull in friends or friends-of-friends so an introduction can happen naturally instead of forcing a cold match.',score:76,status:'available'}];res.json({member,intent,generatedAt:new Date().toISOString(),options})});
function recentAvailability(member){const cutoff=Date.now()-6*60*60*1000,latest=new Map();for(const s of state.signals){if(s.item!=='availability'||new Date(s.createdAt).getTime()<cutoff)continue;latest.set(s.member,s)}return [...latest.values()].filter(x=>x.member!==member).map(x=>({member:x.member,status:x.value,updatedAt:x.createdAt}))}
async function nearbyPlaces(lat,lng,radius=1800){const q=`[out:json][timeout:12];(node["amenity"~"bar|pub|nightclub|restaurant"](around:${radius},${lat},${lng});way["amenity"~"bar|pub|nightclub|restaurant"](around:${radius},${lat},${lng}););out center tags 40;`;const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),9000);try{const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'IN-NYC/1.0'},body:'data='+encodeURIComponent(q),signal:ctl.signal});if(!r.ok)throw new Error('overpass '+r.status);const d=await r.json();return (d.elements||[]).map(e=>{const t=e.tags||{},plat=e.lat||e.center?.lat,plng=e.lon||e.center?.lon;return {id:'osm-'+e.type+'-'+e.id,name:t.name||'',type:t.amenity||'',lat:plat,lng:plng,openingHours:t.opening_hours||'',website:t.website||t['contact:website']||'',street:[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' ')}}).filter(x=>x.name&&x.lat&&x.lng)}finally{clearTimeout(timer)}}
function distMeters(a,b,c,d){const R=6371e3,p1=a*Math.PI/180,p2=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
app.get('/api/fuck-it/live',async(req,res)=>{const member=normalize(req.query.member||'mikey'),lat=Number(req.query.lat),lng=Number(req.query.lng),radius=Math.max(500,Math.min(3500,Number(req.query.radius)||1800)),availability=recentAvailability(member),introductions=datingOptions(member);let places=[],source='network-only';if(Number.isFinite(lat)&&Number.isFinite(lng)&&lat>40&&lat<41&&lng>-75&&lng<-72){try{places=await nearbyPlaces(lat,lng,radius);source='openstreetmap+in-network'}catch(e){console.error('nearby places',e.message)}}const ranked=places.map(p=>{const d=distMeters(lat,lng,p.lat,p.lng),nightBoost=p.type==='nightclub'?30:(p.type==='bar'||p.type==='pub'?22:10),hoursBoost=p.openingHours?4:0;return {...p,distanceMeters:Math.round(d),score:Math.round(120-nightBoost-d/45+hoursBoost)}}).sort((a,b)=>b.score-a.score).slice(0,8);const social=availability.slice(0,8);const top=ranked[0]||null;let move;if(top){const nearbyCount=social.length;move={id:'live-'+Date.now(),label:nearbyCount?'LIVE NYC + YOUR NETWORK':'LIVE NYC',title:`Start at ${top.name}.`,detail:`${top.type==='nightclub'?'Higher-energy room':'Low-commitment first move'} about ${Math.max(1,Math.round(top.distanceMeters/80))} min away on foot. ${nearbyCount?nearbyCount+' people in IN have active availability signals tonight.':'IN will keep watching for people in your network who become available.'}`,place:top,why:[['FRICTION',top.distanceMeters<800?'LOW':'MEDIUM'],['ACTION',top.type==='nightclub'?'VERY HIGH':'HIGH'],['NETWORK',social.length?String(social.length)+' ACTIVE':'QUIET'],['INTRO UPSIDE',introductions.length?'LIVE':'WATCHING'],['UPSIDE','OPEN']]}}else{move={id:'network-'+Date.now(),label:'YOUR NETWORK · RIGHT NOW',title:social.length?'People are moving.':'Open the night.',detail:social.length?`${social.length} people in IN have active availability signals. Start with the network while IN waits for your location to find the room.`:'No live place result yet. Share location when you hit FUCK IT and IN will build from nearby places plus your network.',place:null,why:[['FRICTION','LOW'],['ACTION',social.length?'FORMING':'UNKNOWN'],['NETWORK',social.length?String(social.length)+' ACTIVE':'QUIET'],['INTRO UPSIDE',introductions.length?'LIVE':'WATCHING'],['UPSIDE','OPEN']]}}res.json({member,generatedAt:new Date().toISOString(),source,move,places:ranked,network:{availability:social,introductions:introductions.map(x=>({status:x.status,type:x.type,score:x.score}))}})});
app.post('/api/intro/request',(req,res)=>{const from=normalize(req.body.from),candidate=normalize(req.body.candidate),mode=normalize(req.body.mode||'intro');if(!from)return res.status(400).json({error:'from required'});const rec={id:'req-'+Date.now(),from,candidate:candidate||null,mode,status:candidate?'pending-mutual-consent':'searching',createdAt:new Date().toISOString()};state.introRequests.push(rec);res.json({ok:true,request:rec})});
app.post('/api/reset',(req,res)=>{state.signals.length=0;state.invites.length=0;state.activity.length=0;state.introRequests.length=0;res.json({ok:true})});
registerAgentRoutes(app);
const port=process.env.PORT||3000;initDb().catch(e=>console.error('IN persistence init failed',e)).finally(()=>app.listen(port,()=>{console.log('IN API listening on '+port,'persistence='+(db?'postgres':'memory'));if(process.env.AGENT_AUTO_START_MIKE==='true'&&!latestFor('mikey'))createRun('mikey',process.env.MIKEY_DEFAULT_GOAL||'Continuously surface the most interesting options and possibilities worth caring about right now.')}));