const express=require('express');
const cors=require('cors');
const crypto=require('crypto');
const Stripe=require('stripe');
const {Pool}=require('pg');
const {registerAgentRoutes,createRun,latestFor}=require('./agent-engine');
const app=express();app.use(cors());
const stripe=process.env.STRIPE_SECRET_KEY?new Stripe(process.env.STRIPE_SECRET_KEY):null;
const db=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;
const foundingMembers=['grant','mikey','falconi','stuart','marney'];
const state={signals:[],invites:[],paidMembers:[],activity:[],datingProfiles:[],introRequests:[],networkInvites:[],networkMembers:[],fuckItSessions:[]};
function normalize(x){return String(x||'').trim().toLowerCase()}
function displayName(x){return String(x||'').trim().replace(/\s+/g,' ').slice(0,80)}
function allMemberIds(){return [...new Set([...foundingMembers,...state.networkMembers.map(x=>x.id)])]}
function overlaps(){const by={};for(const s of state.signals){if(!s.item)continue;(by[s.item]??=[]).push(s)}return Object.entries(by).map(([item,arr])=>{const people=[...new Set(arr.map(x=>x.member))];return people.length<2?null:{item,people,score:people.length,latest:arr.at(-1).createdAt}}).filter(Boolean).sort((a,b)=>b.score-a.score)}
async function initDb(){if(!db)return;await db.query(`CREATE TABLE IF NOT EXISTS in_network_invites(id text primary key,token text unique not null,inviter text not null,name text not null,contact text,status text not null,created_at timestamptz not null,opened_at timestamptz,joined_at timestamptz,member_id text);CREATE TABLE IF NOT EXISTS in_network_members(id text primary key,name text not null,contact text,invited_by text,invite_token text unique,interests jsonb not null default '[]'::jsonb,open_to_meet boolean not null default false,gender text,interested_in text,joined_at timestamptz not null);`);const [ir,mr]=await Promise.all([db.query('SELECT * FROM in_network_invites ORDER BY created_at'),db.query('SELECT * FROM in_network_members ORDER BY joined_at')]);state.networkInvites=ir.rows.map(r=>({id:r.id,token:r.token,from:r.inviter,name:r.name,contact:r.contact||'',status:r.status,createdAt:r.created_at?.toISOString(),openedAt:r.opened_at?.toISOString()||null,joinedAt:r.joined_at?.toISOString()||null,memberId:r.member_id||null}));state.networkMembers=mr.rows.map(r=>({id:r.id,name:r.name,contact:r.contact||'',invitedBy:r.invited_by,inviteToken:r.invite_token,interests:r.interests||[],openToMeet:r.open_to_meet,gender:r.gender||'',interestedIn:r.interested_in||'',joinedAt:r.joined_at?.toISOString()}));for(const m of state.networkMembers)if(m.openToMeet&&!state.datingProfiles.some(x=>x.member===m.id))state.datingProfiles.push({member:m.id,gender:m.gender,interestedIn:m.interestedIn,open:true,updatedAt:m.joinedAt})}
async function saveInvite(r){if(!db)return;await db.query(`INSERT INTO in_network_invites(id,token,inviter,name,contact,status,created_at,opened_at,joined_at,member_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,opened_at=EXCLUDED.opened_at,joined_at=EXCLUDED.joined_at,member_id=EXCLUDED.member_id,contact=EXCLUDED.contact`,[r.id,r.token,r.from,r.name,r.contact,r.status,r.createdAt,r.openedAt,r.joinedAt,r.memberId])}
async function saveMember(m){if(!db)return;await db.query(`INSERT INTO in_network_members(id,name,contact,invited_by,invite_token,interests,open_to_meet,gender,interested_in,joined_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,contact=EXCLUDED.contact,interests=EXCLUDED.interests,open_to_meet=EXCLUDED.open_to_meet,gender=EXCLUDED.gender,interested_in=EXCLUDED.interested_in`,[m.id,m.name,m.contact,m.invitedBy,m.inviteToken,JSON.stringify(m.interests),m.openToMeet,m.gender,m.interestedIn,m.joinedAt])}
app.post('/api/billing/webhook',express.raw({type:'application/json'}),(req,res)=>{if(!stripe||!process.env.STRIPE_WEBHOOK_SECRET)return res.status(503).send('Billing not configured');let event;try{event=stripe.webhooks.constructEvent(req.body,req.headers['stripe-signature'],process.env.STRIPE_WEBHOOK_SECRET)}catch(e){return res.status(400).send('Invalid webhook signature')}const o=event.data.object;if(event.type==='checkout.session.completed')state.paidMembers.push({email:normalize(o.customer_details&&o.customer_details.email),customer:o.customer,subscription:o.subscription,status:'paid',createdAt:new Date().toISOString()});res.json({received:true})});
app.use(express.json({limit:'1mb'}));
app.get('/health',(req,res)=>res.json({ok:true,service:'IN shared-signal API',persistence:db?'postgres':'memory',members:allMemberIds().length}));
app.get('/api/state',(req,res)=>{const member=normalize(req.query.member||'grant');res.json({member,members:allMemberIds(),signals:state.signals,overlaps:overlaps(),invites:state.invites.filter(x=>x.to===member||x.from===member)})});
app.post('/api/signal',(req,res)=>{const member=normalize(req.body.member),item=normalize(req.body.item),value=String(req.body.value||'');if(!member||!item||!value)return res.status(400).json({error:'member, item, value required'});const rec={id:Date.now()+'-'+Math.random().toString(36).slice(2,7),member,item,value,createdAt:new Date().toISOString()};state.signals.push(rec);if(state.signals.length>5000)state.signals.splice(0,state.signals.length-5000);res.json({ok:true,signal:rec,overlaps:overlaps()})});
app.post('/api/invite',(req,res)=>{const from=normalize(req.body.from),to=normalize(req.body.to),item=normalize(req.body.item);if(!from||!to||!item)return res.status(400).json({error:'from, to, item required'});const rec={id:Date.now()+'-'+Math.random().toString(36).slice(2,7),from,to,item,status:'open',createdAt:new Date().toISOString()};state.invites.push(rec);res.json({ok:true,invite:rec})});
app.post('/api/activity',(req,res)=>{const member=normalize(req.body.member),event=normalize(req.body.event),detail=String(req.body.detail||''),sessionId=String(req.body.sessionId||'').slice(0,120);if(!member||!event)return res.status(400).json({error:'member and event required'});const rec={id:Date.now()+'-'+Math.random().toString(36).slice(2,7),member,event,detail,sessionId,createdAt:new Date().toISOString()};state.activity.push(rec);console.log('ACTIVITY',JSON.stringify(rec));res.json({ok:true,activity:rec})});
app.get('/api/activity',(req,res)=>{const member=normalize(req.query.member||'mikey'),rows=state.activity.filter(x=>x.member===member).slice(-200).reverse();res.json({member,count:rows.length,activity:rows})});
app.post('/api/network/invite',async(req,res)=>{try{const from=normalize(req.body.from),name=displayName(req.body.name),contact=String(req.body.contact||'').trim().slice(0,160);if(!from||!name)return res.status(400).json({error:'from and name required'});const token=crypto.randomBytes(18).toString('hex'),rec={id:'in-'+Date.now(),token,from,name,contact,status:'sent',createdAt:new Date().toISOString(),openedAt:null,joinedAt:null,memberId:null};state.networkInvites.push(rec);await saveInvite(rec);res.json({ok:true,invite:{...rec,url:(process.env.IN_SITE_URL||'https://yourein.co')+'/accept-in.html?token='+token}})}catch(e){res.status(500).json({error:'Could not create invite'})}});
app.get('/api/network/invite/:token',async(req,res)=>{const rec=state.networkInvites.find(x=>x.token===req.params.token);if(!rec)return res.status(404).json({error:'Invite not found'});if(!rec.openedAt){rec.openedAt=new Date().toISOString();rec.status=rec.status==='joined'?'joined':'opened';await saveInvite(rec)}res.json({invite:rec})});
app.post('/api/network/join',async(req,res)=>{try{const token=String(req.body.token||''),rec=state.networkInvites.find(x=>x.token===token);if(!rec)return res.status(404).json({error:'Invite not found'});const name=displayName(req.body.name||rec.name),contact=String(req.body.contact||rec.contact||'').trim().slice(0,160),interests=Array.isArray(req.body.interests)?req.body.interests.slice(0,12):[],openToMeet=!!req.body.openToMeet,gender=normalize(req.body.gender),interestedIn=normalize(req.body.interestedIn);let base=normalize(name).replace(/[^a-z0-9]+/g,'-')||'member',id=base,n=2;while(allMemberIds().includes(id))id=base+'-'+n++;const member={id,name,contact,invitedBy:rec.from,inviteToken:token,interests,openToMeet,gender,interestedIn,joinedAt:new Date().toISOString()};state.networkMembers.push(member);rec.status='joined';rec.joinedAt=member.joinedAt;rec.memberId=id;if(openToMeet)state.datingProfiles.push({member:id,gender,interestedIn,open:true,updatedAt:member.joinedAt});await saveMember(member);await saveInvite(rec);res.json({ok:true,member})}catch(e){res.status(500).json({error:'Could not join IN'})}});
app.get('/api/network/members',(req,res)=>res.json({count:state.networkMembers.length,members:state.networkMembers,foundingMembers}));
app.get('/api/network/invites',(req,res)=>{const from=normalize(req.query.from||'');res.json({invites:state.networkInvites.filter(x=>!from||x.from===from)})});
app.post('/api/dating/profile',(req,res)=>{const member=normalize(req.body.member),gender=normalize(req.body.gender),interestedIn=normalize(req.body.interestedIn),open=!!req.body.open;let p=state.datingProfiles.find(x=>x.member===member);if(!p){p={member};state.datingProfiles.push(p)}Object.assign(p,{gender,interestedIn,open,updatedAt:new Date().toISOString()});res.json({ok:true,profile:p})});
function datingOptions(member){const me=state.datingProfiles.find(x=>x.member===member);return state.datingProfiles.filter(x=>x.member!==member&&x.open&&(!me?.interestedIn||me.interestedIn==='any'||x.gender===me.interestedIn)&&(!x.interestedIn||x.interestedIn==='any'||x.interestedIn===me?.gender)).map(x=>({candidate:x.member,status:'available'}))}
function recentAvailability(member){const cutoff=Date.now()-6*60*60*1000,latest=new Map();for(const s of state.signals){if(s.item==='availability'&&new Date(s.createdAt).getTime()>=cutoff)latest.set(s.member,s)}return [...latest.values()].filter(x=>x.member!==member).map(x=>({member:x.member,status:x.value,updatedAt:x.createdAt}))}
const curatedNYC=[
{id:'curated-little-branch',name:'Little Branch',type:'bar',street:'20 7th Ave S',neighborhood:'West Village',why:'A strong first move when the night needs atmosphere without turning into a giant production.',source:'curated',verifiedAt:'2026-09-07'},
{id:'curated-art-bar',name:'Art Bar',type:'bar',street:'52 8th Ave',neighborhood:'West Village',why:'Low-friction, social, and easy to use as a launch point before the night changes.',source:'curated',verifiedAt:'2026-09-07'},
{id:'curated-katana-kitten',name:'Katana Kitten',type:'bar',street:'531 Hudson St',neighborhood:'West Village',why:'Higher-upside cocktail move with enough personality to feel like an actual night.',source:'curated',verifiedAt:'2026-09-07'},
{id:'curated-jimmy',name:'JIMMY',type:'bar',street:'15 Thompson St',neighborhood:'SoHo',why:'A downtown rooftop move when Mikey wants more energy and a bigger swing.',source:'curated',verifiedAt:'2026-09-07'},
{id:'curated-warrenpeace',name:'WarrenPeace',type:'bar',street:'77 Warren St',neighborhood:'Tribeca',why:'A polished Tribeca option that can work as the first stop or a date/introduction setting.',source:'curated',verifiedAt:'2026-09-07'},
{id:'curated-brandylibrary',name:'Brandy Library',type:'bar',street:'25 N Moore St',neighborhood:'Tribeca',why:'A seated, elevated fallback when the night needs conversation rather than chaos.',source:'curated',verifiedAt:'2026-09-07'},
{id:'curated-owls-tail',name:'The Owl’s Tail',type:'bar',street:'215 W 75th St',neighborhood:'Upper West Side',why:'A downtown-feeling cocktail move without making Mikey cross the city first.',source:'curated',verifiedAt:'2026-09-07'}
];
async function queryOverpass(endpoint,q){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),1600);try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'IN-NYC/1.2'},body:'data='+encodeURIComponent(q),signal:ctl.signal});if(!r.ok)throw new Error('provider '+r.status);const d=await r.json();const places=(d.elements||[]).map(e=>{const t=e.tags||{};return {id:'osm-'+e.id,name:t.name||'',type:t.amenity||'',lat:e.lat||e.center?.lat,lng:e.lon||e.center?.lon,street:[t['addr:housenumber'],t['addr:street']].filter(Boolean).join(' '),source:'openstreetmap'}}).filter(x=>x.name&&x.lat&&x.lng);if(!places.length)throw new Error('empty provider');return places}finally{clearTimeout(timer)}}
async function nearbyPlaces(lat,lng,radius=1800){const q=`[out:json][timeout:4];(node["amenity"~"bar|pub|nightclub|restaurant"](around:${radius},${lat},${lng});way["amenity"~"bar|pub|nightclub|restaurant"](around:${radius},${lat},${lng}););out center tags 40;`;const mirrors=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.nchc.org.tw/api/interpreter'];try{return await Promise.any(mirrors.map(x=>queryOverpass(x,q)))}catch(e){console.error('all place providers failed fast');return []}}
function distMeters(a,b,c,d){const R=6371e3,p1=a*Math.PI/180,p2=c*Math.PI/180,dp=(c-a)*Math.PI/180,dl=(d-b)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function facilitatorPool(livePlaces,step){const live=livePlaces.filter(p=>['bar','pub','nightclub','restaurant'].includes(p.type));const fallback=[...curatedNYC.slice(step%curatedNYC.length),...curatedNYC.slice(0,step%curatedNYC.length)];const seen=new Set();return [...live,...fallback].filter(p=>{const k=normalize(p.name);if(seen.has(k))return false;seen.add(k);return true})}
function orchestrate(member,places,availability,intros,step=0){const pool=facilitatorPool(places,step),social=pool.filter(p=>['bar','pub','nightclub'].includes(p.type)),start=social[0]||pool[0],second=social.find(p=>p.id!==start?.id&&p.neighborhood!==start?.neighborhood)||social.find(p=>p.id!==start?.id)||pool.find(p=>p.id!==start?.id),person=availability[0]||null,intro=intros[0]||null;const beats=[];if(start)beats.push({when:'START NOW',title:start.name,detail:(start.street?start.street+' · ':'')+(start.why||'This is the opening move. Give it 30 minutes, then tell IN whether the room has it.'),place:start});if(second)beats.push({when:'SECOND MOVE',title:second.name,detail:(second.street?second.street+' · ':'')+'IN is holding this as the pivot. Do not commit yet; use it if the first move does not have momentum.',place:second});const people=person?{status:'active',title:displayName(person.member)+' is '+person.status+'.',detail:'IN can pull them into this session now.',actions:[{label:'PING '+displayName(person.member).toUpperCase(),member:person.member}]}:{status:'watching',title:'Nobody in your circle has signaled yet.',detail:'That does not stop the night. IN is still watching Grant, Stuart, Falconi and the rest of your network.',actions:['grant','stuart','falconi'].filter(x=>x!==member).map(x=>({label:'PING '+x.toUpperCase(),member:x}))};const introduction=intro?{status:'possible',title:'There is a legitimate introduction path.',detail:'IN can privately check both sides. Nobody is revealed until interest is mutual.'}:{status:'watching',title:'No mutual introduction is ready yet.',detail:'IN is watching for a consented introduction that actually improves the night.'};const watching=['Your network becoming available','A better second move nearby','A legitimate mutual introduction','Signals that the current room is dead'];return {id:'fx-'+Date.now(),mode:'facilitator',status:'proposed',headline:(member==='mikey'?'Mikey. Here’s your night.':'Here’s your night.'),subhead:'IN made the opening move. Now it stays with the night.',start,secondMove:second,people,introduction,watching,beats,ingredients:{place:!!start,network:!!person,introduction:!!intro,livePlace:!!places.length},canInvite:!!person,inviteMember:person?.member||null,truth:{liveVenueData:!!places.length,networkSignal:!!person,mutualIntro:!!intro,curatedFallback:!places.length}}}
app.get('/api/fuck-it/live',async(req,res)=>{const member=normalize(req.query.member||'mikey'),lat=Number(req.query.lat),lng=Number(req.query.lng),radius=Math.max(800,Math.min(5000,Number(req.query.radius)||2200)),step=Math.max(0,Number(req.query.step)||0),availability=recentAvailability(member),introductions=datingOptions(member);let places=[];const hasLocation=Number.isFinite(lat)&&Number.isFinite(lng)&&lat>40&&lat<41&&lng>-75&&lng<-72;if(hasLocation){try{places=await nearbyPlaces(lat,lng,radius)}catch(e){console.error('nearby',e.message)}}if(hasLocation)places=places.map(p=>({...p,distanceMeters:Math.round(distMeters(lat,lng,p.lat,p.lng))})).sort((a,b)=>a.distanceMeters-b.distanceMeters).slice(0,12);const experience=orchestrate(member,places,availability,introductions,step);res.json({member,generatedAt:new Date().toISOString(),experience,places:places.length?places:curatedNYC,network:{availability,introductions:introductions.map(x=>({status:x.status}))},facilitator:{locationReceived:hasLocation,venueSource:places.length?'live-nearby':'curated-nyc-fallback',sessionWindowMinutes:180,responseMode:'fail-open-fast'}})});
app.post('/api/fuck-it/session',(req,res)=>{const member=normalize(req.body.member||'mikey'),action=normalize(req.body.action),experience=req.body.experience||{},rec={id:'session-'+Date.now(),member,action,status:action==='accept'?'active':action==='out'?'ended':'adapting',experience,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+3*60*60*1000).toISOString()};state.fuckItSessions.push(rec);if(state.fuckItSessions.length>500)state.fuckItSessions.shift();res.json({ok:true,session:rec})});
app.post('/api/intro/request',(req,res)=>{const from=normalize(req.body.from),candidate=normalize(req.body.candidate),mode=normalize(req.body.mode||'intro');const rec={id:'req-'+Date.now(),from,candidate:candidate||null,mode,status:candidate?'pending-mutual-consent':'searching',createdAt:new Date().toISOString()};state.introRequests.push(rec);res.json({ok:true,request:rec})});
app.post('/api/reset',(req,res)=>{state.signals.length=0;state.invites.length=0;state.activity.length=0;state.introRequests.length=0;res.json({ok:true})});
registerAgentRoutes(app);
const port=process.env.PORT||3000;initDb().catch(e=>console.error('IN persistence init failed',e)).finally(()=>app.listen(port,()=>console.log('IN API listening on '+port)));